print("Enter a name below.")
Name0 = input()
print("Enter a second name below.")
name1 = input()
print("Enter a location below.")
Location0 = input()
print("Enter an adjective below.")
adj1 = input()
print ("Once upon a time, there was a person named " + Name0 + ". He was a brave warrior in the land of " + Location0 + ". One night, a person named " + name1 + " came while everyone was sleeping and sent an attack to come the following morning. In the morning, the king heard this news and sent " + Name0 + " to " + adj1 + " the building. The attack finally came, and was defeated. " + Name0 + " was kinged, the land was saved, and " + name1 + " never came again. The end.")